workflows:
  android-release:
    name: Android Release APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.44.1
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios-release:
    name: iOS Release IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.44.1
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
      - mkdir -p Payload
      - cp -r build/ios/iphoneos/Runner.app Payload/
      - zip -r app.ipa Payload/
    artifacts:
      - app.ipa
